### ISSUE TITLE
Added Logo and social link of the Open Horizon 

### ISSUE THREAD

**Issue by Ayush7614** [open-horizon/.github#1]
Created Profile Folder and in profile folder created Readme that will appear on the orgazination profile and added logo of the orgazination and added all the social links of the open horizon

**Comment by joewxboy** [comment]
Thanks.  Can you also add links to:
* Our Code of Conduct: https://lfprojects.org/policies/code-of-conduct/
* Anti-trust Policy: https://lfprojects.org/policies/antitrust-policy/
* Documentation site: https://open-horizon.github.io/
* Chat server: https://chat.lfx.linuxfoundation.org/
* Mailing list: https://lists.lfedge.org/g/open-horizon

**Comment by Ayush7614** [comment]
> Thanks. Can you also add links to:
> 
> * Our Code of Conduct: https://lfprojects.org/policies/code-of-conduct/
> * Anti-trust Policy: https://lfprojects.org/policies/antitrust-policy/
> * Documentation site: https://open-horizon.github.io/
> * Chat server: https://chat.lfx.linuxfoundation.org/
> * Mailing list: https://lists.lfedge.org/g/open-horizon

Sure I am adding all this things

**Comment by rgrupesh** [comment]
@joewxboy @Ayush7614 

I think it would be helpful to have some sort of appendix at the bottom. We can use that to include common yet confusing terms used in the project. Also, can we add an overall roadmap for the project? It could surely help new contributors to better understand the project.

**Comment by Akshit42-hue** [comment]
We can also add FAQ in the readme file that gives a clear idea for the new contributors
@joewxboy @Ayush7614 @rgrupesh . What's your take on this?

**Comment by Abhijay007** [comment]
@joewxboy @Ayush7614 I also have some suggestions, look how layer5 did this for their main repo, I liked the way how they displayed all their Projects and their description in their readme, we can also do something like that :  (https://github.com/layer5io), it will help very helpfull for the new contributor to navigate between direct projects and see all the tech we have, if not for this repo, we can do it for the main org one, what are your thoughts on this?

**Comment by joewxboy** [comment]
> @joewxboy @Ayush7614
> 
> I think it would be helpful to have some sort of appendix at the bottom. We can use that to include common yet confusing terms used in the project. Also, can we add an overall visual roadmap for the project? It could surely help new contributors to better understand the project.

Good thinking.  If it's too much information, then at least a link to a Glossary of Terms.
