### ISSUE TITLE
Added Contributing and Contribution Guidelines

### ISSUE THREAD

**Issue by Ayush7614** [open-horizon/.github#11]
Added Contributing Guidelines Files
Added Contribution Guidelines Files

**Comment by Ayush7614** [comment]
@joewxboy 
Please assign me this issue

**Comment by joewxboy** [comment]
We should create:

1. `CONTRIBUTING.md` file in `.github` repo that gives high-level (simple) instructions and guidelines, and links to other locations for more details.  Other locations may include:

* [Documentation web site](https://open-horizon.github.io/common-requests/contribute.html)
* [Project wiki](https://wiki.lfedge.org/display/OH/Project+Contributions)
* Anywhere else that I missed?

2. Edit `.github/profile/README.md` to add a link to the `CONTRIBUTING.md` file.

3. Edit the "other locations" in point one above to add links to the `CONTRIBUTING.md` file.  This will require creating a separate issue for updating the documentation page in the `open-horizon.github.io` repo and linking that issue to this one as a dependency.

**Comment by joewxboy** [comment]
Fixed by pr #13
