### ISSUE TITLE
Working Groups Templates

### ISSUE THREAD

**Issue by Ayush7614** [open-horizon/.github#12]
We Can also Add Working Group Templates which contains all the meeting notes like this 
![image](https://user-images.githubusercontent.com/67006255/156776615-50f638dc-19f9-4310-a8db-b2cd25e75eab.png)
![image](https://user-images.githubusercontent.com/67006255/156776651-82b54a28-1533-4fd3-858a-a48549344559.png)
Like This

**Comment by Ayush7614** [comment]
@joewxboy

**Comment by joewxboy** [comment]
@Ayush7614 Something like this? https://wiki.edgexfoundry.org/display/FA/2022-03-03+Meeting+record

If so, the Confluence Wiki software can do this for us.  We just need to begin using that for our meetings instead of the single page list of slides and recordings.

**Comment by joewxboy** [comment]
@Ayush7614 Here's an example of how it would look for us in DWG: https://wiki.lfedge.org/display/OH/2022-03-08+Meeting+notes

**Comment by Ayush7614** [comment]
> @Ayush7614 Here's an example of how it would look for us in DWG: https://wiki.lfedge.org/display/OH/2022-03-08+Meeting+notes

Yes it is same as

**Comment by joewxboy** [comment]
OK so it sounds like I can close this issue and we can just use the template in the wiki. Is that right?

**Comment by Ayush7614** [comment]
> OK so it sounds like I can close this issue and we can just use the template in the wiki. Is that right?

Actually i use this template here also like all the meeting things was also in this repo and it contains all the information of open horizon there is one seperate directory was there name "working groups/tempaltes/meetingnotes" this is the idea of make this template

**Comment by joewxboy** [comment]
Closing this issue since we're trying to keep all meeting-related notes in the project wiki under community.
