### ISSUE TITLE
Create SECURITY.md file

### ISSUE THREAD

**Issue by joewxboy** [open-horizon/.github#20]
Describe OpenSSL critical vulnerability, how it affects Open Horizon, and our plans to mitigate.  
Describe how to contact Open Horizon with any discovered vulnerabilities.
Link to any relevant documentation.

FYI: @dabooz and @johnwalicki

**Comment by johnwalicki** [comment]
Let's use this issue to improve upon our adherence to the OpenSSF Best Practices guidelines.  One of the 
https://github.com/coreinfrastructure/best-practices-badge
recommendations is to include a SECURITY.md which details the procedure for responsible disclosure of vulnerabilities.

**Comment by johnwalicki** [comment]
The basic template of this file is quite simple.
```markdown
# Security Policy
## Reporting a Vulnerability
Please report any potential security issues to `emailaddress@example.com`. This will notify the core project team who will respond accordingly.
```

**Comment by johnwalicki** [comment]
Our implementation will have a way to post to LF managed secure mailing list.  The Open Horizon maintainers will be subscribed to this private list. 

@joewxboy is working with the LF infrastructure team to establish that mailing list.
