### ISSUE TITLE
Fix Install the Management Hub Services link

### ISSUE THREAD

**Issue by t-fine** [open-horizon/.github#25]
On the Open Horizon project GitHub home page (https://github.com/open-horizon) the "Install the Management Hub Services" link points to an outdated GitHub page here: https://github.com/open-horizon/devops/blob/master/mgmt-hub/README.md#-deploy-all-in-1-horizon-management-hub-agent-and-cli 

That page then instructs the user to go to the new and correct documentation page: https://open-horizon.github.io/docs/mgmt-hub/docs/index.html

I propose we change the link on the landing page to go directly to the new documentation page.

The `README.md` file to modify can be found here: https://github.com/open-horizon/.github/blob/master/profile/README.md

**Comment by t-fine** [comment]
@eabraze can do!

**Comment by joewxboy** [comment]
Fixed in PR #27
