### ISSUE TITLE
Broken link to Getting Involved with LF Edge

### ISSUE THREAD

**Issue by marhabac33** [open-horizon/.github#29]
https://github.com/open-horizon/.github/blob/81e94be1397703abb613b758dee52be32be93cd7/profile/README.md?plain=1#L43

Current link gives `404`
It should be updated to https://lfedge.org/resources/get-involved/

**Comment by joewxboy** [comment]
Thanks, @marhabac33 .  Were you interested in working on this?

**Comment by marhabac33** [comment]
@joewxboy sure. I can work on it.
